language: rust

stages:
  - test
  - name: "Build docker examples"
    if: branch = master

matrix:
  fast_finish: true
  include:
    - stage: test
      name: stable
      env: CACHE_JOB=stable
      rust: stable
    - stage: test
      name: beta
      env: CACHE_JOB=beta
      rust: stable
    - stage: test
      name: nightly
      env: CACHE_JOB=nightly
      rust: stable
    - stage: test
      name: rustfmt
      env: CACHE_JOB=stable
      rust: stable
      install:
        - rustup component add rustfmt
      script:
        - cargo fmt -- --check
    - stage: test
      name: clippy
      env: CACHE_JOB=stable
      rust: stable
      install:
        - rustup component add clippy
      script:
        - cargo clippy
    - stage: "Build docker examples"
      rust: stable
      env: EXAMPLE=simple_hello_world
      script:
        - |
          docker build --build-arg EXAMPLE=$EXAMPLE . -t mockersf/concourse-resource-rs-examples:$EXAMPLE
          docker login -u "$DOCKER_LOGIN" -p "$DOCKER_PASSWORD"
          docker push mockersf/concourse-resource-rs-examples:$EXAMPLE
    - stage: "Build docker examples"
      rust: stable
      env: EXAMPLE=hello_world
      script:
        - |
          docker build --build-arg EXAMPLE=$EXAMPLE . -t mockersf/concourse-resource-rs-examples:$EXAMPLE
          docker login -u "$DOCKER_LOGIN" -p "$DOCKER_PASSWORD"
          docker push mockersf/concourse-resource-rs-examples:$EXAMPLE

cache:
  - cargo

script:
  - cargo test
